<?php

$sql_after_education = "SELECT
H1.[O_HMEN01_ID]
,H1.[REGION_COD]
,AFTER_EDUCATION.[O_HMEN09_ID] as AFTER_EDU_ID
,AFTER_EDUCATION.[M_EDU_03_ID] as AFTER_DEGREECODE
,AFTER_EDUCATION.[SPECIAL] as AFTER_EDU_SPEC
,AFTER_EDUCATION.[DATE] as AFTER_EDU_DATE
,EDUC_SPRAV.[NAME] as AFTER_EDU_ZVANIE

FROM [Kadry2024v2].[dbo].[O_HMEN01] H1

JOIN [Kadry2024v2].[dbo].[O_HMEN09] AFTER_EDUCATION
ON H1.[REGION_COD] = AFTER_EDUCATION.[REGION_COD] and H1.[O_HMEN01_ID] = AFTER_EDUCATION.[O_HMEN01_ID]

LEFT JOIN [Kadry2024v2].[dbo].[M_EDU_03] EDUC_SPRAV
ON AFTER_EDUCATION.[M_EDU_03_ID] = EDUC_SPRAV.[M_EDU_03_ID]

Order by H1.[REGION_COD], H1.[O_HMEN01_ID],AFTER_EDUCATION.[DATE]
";

?>