<?php

$sql_contracts = "SELECT
  H1.[O_HMEN01_ID]
  ,H1.[REGION_COD]
  ,CONTR.[O_CONTRACT_ID] as CONTRACT_ID
  ,CONTR.[M_VidContractID] as CONTRACT_TYPE
  ,CONTR.[DATEBEGIN] as CONTRACT_BEGIN
  ,CONTR.[DATEFINISH] as CONTRACT_END
  ,SRT.[O_SRT_ID] as SRT_ID
  ,SRT.[STAVKA] as STAVKA
  ,SRT.[DATEBEGIN] as STAVKA_BEGIN
  ,TRUD_DOGOVOR.[NAME] AS trud_name
  ,TRUD_DOGOVOR.[NUM] as trud_number
  ,TRUD_DOGOVOR.[DATE] as trud_date
  ,WFl.[M_ORD_02_ID]
  ,WFl.[DATEFINISH]
  ,WFl.[M_ORD_01_ID]
  ,REESTR.[FullName] as REESTR_FULLNAME

  FROM [Kadry2024v2].[dbo].[O_HMEN01] H1

  LEFT JOIN [Kadry2024v2].[dbo].[O_WFL_01] WFl
  ON H1.[O_HMEN01_ID] = WFl.[O_HMEN01_ID] AND H1.[REGION_COD] = WFl.[REGION_COD]

  LEFT JOIN [Kadry2024v2].[dbo].[O_SRT] SRT
  ON WFl.[O_SRT_ID] = SRT.[O_SRT_ID] AND WfL.[REGION_COD] = SRT.[REGION_COD]

  LEFT JOIN [Kadry2024v2].[dbo].[O_CONTRACT] CONTR
  ON H1.[O_HMEN01_ID] = CONTR.[O_HMEN01_ID] and H1.[REGION_COD] = CONTR.[REGION_COD]

  left join [Kadry2024v2].[dbo].[O_ORD_01] TRUD_DOGOVOR
  on CONTR.[O_ORD_01_ID] = TRUD_DOGOVOR.[O_ORD_01_ID] and WFl.[REGION_COD] = TRUD_DOGOVOR.[REGION_COD] and (TRUD_DOGOVOR.[M_ORD_03_ID] = 21 or TRUD_DOGOVOR.[M_ORD_03_ID] = 22)

  left join [Kadry2024v2].[dbo].[O_REESTR] REESTR
  on SRT.[O_REESTR_ID] = REESTR.[O_REESTR_ID]

  WHERE WFl.[O_SRT_ID] IS NOT NULL

  Order By H1.[REGION_COD],H1.[O_HMEN01_ID],CONTR.[DATEBEGIN], WFl.[DATEFINISH], WFl.[M_ORD_01_ID] DESC
  ";

// $sql_contracts = "SELECT
// H1.[O_HMEN01_ID]
// ,H1.[REGION_COD]
// ,CONTR.[O_CONTRACT_ID] as CONTRACT_ID
// ,CONTR.[M_VidContractID] as CONTRACT_TYPE
// ,CONTR.[DATEBEGIN] as CONTRACT_BEGIN
// ,CONTR.[DATEFINISH] as CONTRACT_END
// ,SRT.[O_SRT_ID] as SRT_ID
// ,SRT.[STAVKA] as STAVKA
// ,SRT.[DATEBEGIN] as STAVKA_BEGIN
// --,OKLAD.[O_OKLAD_ID] AS OKLAD_ID
// --,OKLAD.[OKLAD_VALUE] AS RAZMER_OKLADA
// --,OKLAD.[DATEBEGIN] AS BEGIN_OKLAD
// --,OKLAD.[DATEFINISH] AS FINISH_OKLAD
// ,TRUD_DOGOVOR.[NAME] AS trud_name
// ,TRUD_DOGOVOR.[NUM] as trud_number
// ,TRUD_DOGOVOR.[DATE] as trud_date
// ,WFl.[M_ORD_02_ID]
// ,WFl.[DATEFINISH]
// ,WFl.[M_ORD_01_ID]
// ,REESTR.[FullName] as REESTR_FULLNAME

//   FROM [Kadry2024v2].[dbo].[O_HMEN01] H1

//   LEFT JOIN [Kadry2024v2].[dbo].[O_WFL_01] WFl
//   ON H1.[O_HMEN01_ID] = WFl.[O_HMEN01_ID] AND H1.[REGION_COD] = WFl.[REGION_COD]
  
//   LEFT JOIN [Kadry2024v2].[dbo].[O_SRT] SRT
//   ON WFl.[O_SRT_ID] = SRT.[O_SRT_ID] AND WfL.[REGION_COD] = SRT.[REGION_COD]
  
//   LEFT JOIN [Kadry2024v2].[dbo].[O_CONTRACT] CONTR
//   ON H1.[O_HMEN01_ID] = CONTR.[O_HMEN01_ID] and H1.[REGION_COD] = CONTR.[REGION_COD]
  
//   --LEFT JOIN [Kadry2024v2].[dbo].[O_OKLAD] OKLAD
//   --ON SRT.[O_REESTR_ID] = OKLAD.[O_REESTR_ID]

//   left join [Kadry2024v2].[dbo].[O_REESTR] REESTR
//   on SRT.[O_REESTR_ID] = REESTR.[O_REESTR_ID]
  
//   LEFT JOIN [Kadry2024v2].[dbo].[O_ORD_01] DOCS
//   ON WFl.[O_ORD_01_ID] = DOCS.[O_ORD_01_ID] AND WFl.[REGION_COD] = DOCS.[REGION_COD]

//   left join [Kadry2024v2].[dbo].[O_ORD_01] TRUD_DOGOVOR
//   on WFl.[O_ORD_01_ID] = DOCS.[O_ORD_01_ID] and WFl.[REGION_COD] = DOCS.[REGION_COD] and DOCS.[M_ORD_03_ID] = 21
  
//   WHERE WFl.[O_SRT_ID] IS NOT NULL 
//   --and WFL.[M_ORD_01_ID] != 11
//   --AND WFl.[DATEFINISH] IS NULL 
//   --and OKLAD.[DATEFINISH] is null
  
//   Order By H1.[REGION_COD],H1.[O_HMEN01_ID]
//   ";

  ?>