<?php

$sql_vacations2 = "SELECT
H1.[O_HMEN01_ID]
,H1.[REGION_COD]
,OTPUSK.[O_HDAY02_ID]
,OTPUSK_SPRAVOCHNIK.[NAME]
,OTPUSK.[DATEBEGIN]
,OTPUSK.[DATEFINISH]

FROM [Kadry2024v2].[dbo].[O_HMEN01] H1

inner JOIN [Kadry2024v2].[dbo].[O_HDAY02] OTPUSK
ON H1.[O_HMEN01_ID] = OTPUSK.[O_HMEN01_ID] AND H1.[REGION_COD] = OTPUSK.[REGION_COD]
LEFT JOIN [Kadry2024v2].[dbo].[M_HDAY02] OTPUSK_SPRAVOCHNIK
ON OTPUSK.[M_HDAY02_ID] = OTPUSK_SPRAVOCHNIK.[M_HDAY02_ID]

WHERE OTPUSK.[M_HDAY02_ID] != 42
Order by H1.[REGION_COD], H1.[O_HMEN01_ID], OTPUSK.[O_HDAY02_ID]
"

?>