<?php

// $sql_doljnosti = "SELECT
//       H1.[O_HMEN01_ID]
//       ,H1.[REGION_COD]
//       ,WFl.[O_WFL_01_ID] as STAJ_ID
//       ,SRT.[O_SRT_ID] as SRT_ID
//       ,SRT.[STAVKA] as STAVKA
//       ,SRT.[DATEBEGIN] as STAVKA_BEGIN
//       ,SRT.[DATEFINISH] as STAVKA_END
//       ,WFl.[DATEBEGIN] as STAJ_BEGIN
//       ,WFl.[DATEFINISH] as STAJ_END
//       ,WFl.[M_ORD_01_ID] as OSNOVANIE_TYPE
//       ,WFl.[M_ORD_02_ID] as OSNOVANIE_CODE

//         FROM [Kadry2024v2].[dbo].[O_HMEN01] H1

//         LEFT JOIN [Kadry2024v2].[dbo].[O_WFL_01] WFl
//         ON H1.[O_HMEN01_ID] = WFl.[O_HMEN01_ID] AND H1.[REGION_COD] = WFl.[REGION_COD]
        
//         LEFT JOIN [Kadry2024v2].[dbo].[O_SRT] SRT
//         ON WFl.[O_SRT_ID] = SRT.[O_SRT_ID] AND WfL.[REGION_COD] = SRT.[REGION_COD]
        
//         WHERE WFl.[O_SRT_ID] IS NOT NULL AND WFl.[O_ORD_01_ID] IS NOT NULL
//         AND WFl.[M_ORD_01_ID] != 11
        
//         ORDER BY WFl.[O_WFL_01_ID]
//   ";

$sql_doljnosti = "SELECT
H1.[O_HMEN01_ID]
,H1.[REGION_COD]
,WFl.[O_WFL_01_ID] as STAJ_ID
,SRT.[O_SRT_ID] as SRT_ID
,SRT.[STAVKA] as STAVKA
,SRT.[DATEBEGIN] as STAVKA_BEGIN
,SRT.[DATEFINISH] as STAVKA_END
,WFl.[DATEBEGIN] as STAJ_BEGIN
,WFl.[DATEFINISH] as STAJ_END
,WFl.[M_ORD_01_ID] as OSNOVANIE_TYPE
,WFl.[M_ORD_02_ID] as OSNOVANIE_CODE

,PRIKAZI.[NAME] as PRIEM_PRIKAZ_NAME
,PRIKAZI.[NUM] as PRIEM_PRIKAZ_NUM
,PRIKAZI.[DATE] as PRIEM_PRIKAZ_DATE

,WFl2.[M_ORD_01_ID] as RETIRE_TYPE
,WFl2.[M_ORD_02_ID] as RETIRE_CODE

,PRIKAZI2.[NAME] as RETIRE_PRIKAZ_NAME
,PRIKAZI2.[NUM] as RETIRE_PRIKAZ_NUM
,PRIKAZI2.[DATE] as RETIRE_PRIKAZ_DATE

FROM [Kadry2024v2].[dbo].[O_HMEN01] H1

LEFT JOIN [Kadry2024v2].[dbo].[O_WFL_01] WFl
  ON  H1.[O_HMEN01_ID] = WFl.[O_HMEN01_ID] AND 
      H1.[REGION_COD] = WFl.[REGION_COD] and
      WFl.[M_ORD_01_ID] != 11 and
      WFl.[O_SRT_ID] IS NOT NULL AND
      WFl.[O_ORD_01_ID] IS NOT NULL
  
LEFT JOIN [Kadry2024v2].[dbo].[O_SRT] SRT
  ON  WFl.[O_SRT_ID] = SRT.[O_SRT_ID] AND 
      WfL.[REGION_COD] = SRT.[REGION_COD] 
      
LEFT JOIN [Kadry2024v2].[dbo].[O_ORD_01] PRIKAZI
	ON WFl.[REGION_COD] = PRIKAZI.[REGION_COD] AND WFl.[O_ORD_01_ID] = PRIKAZI.[O_ORD_01_ID]
  
LEFT JOIN [Kadry2024v2].[dbo].[O_WFL_01] WFl2
  ON  H1.[O_HMEN01_ID] = WFl2.[O_HMEN01_ID] AND 
      H1.[REGION_COD] = WFl2.[REGION_COD] and 
      WFl2.[M_ORD_01_ID] = 11 and 
      WFl2.[O_SRT_ID] IS NOT NULL AND 
      WFl2.[O_ORD_01_ID] IS NOT NULL 
      AND WFl2.[DATEFINISH] = WFl.[DATEFINISH]
  
LEFT JOIN [Kadry2024v2].[dbo].[O_ORD_01] PRIKAZI2
	ON WFl2.[REGION_COD] = PRIKAZI2.[REGION_COD] AND WFl2.[O_ORD_01_ID] = PRIKAZI2.[O_ORD_01_ID]    
  
WHERE 
  WFl.[O_SRT_ID] IS NOT NULL AND
  WFl.[O_ORD_01_ID] IS NOT NULL

ORDER BY WFl.[O_WFL_01_ID]
  ";

  ?>