<?php

$sql_sickpregnant = "SELECT
OTPUSK.[O_HMEN01_ID]
,OTPUSK.[REGION_COD]
,OTPUSK.[O_HDAY02_ID]
,OTPUSK_SPRAVOCHNIK.[NAME]
,OTPUSK.[DATEBEGIN]
,OTPUSK.[DATEFINISH]
,OTPUSK.[O_ORD_01_ID] as DOC_ID
,DOCUMENTS.[NAME] as DOC_NAME
,DOCUMENTS.[NUM] as DOC_NUM
,DOCUMENTS.[DATE] as DOC_DATE

FROM [Kadry2024v2].[dbo].[O_HMEN01] H1

inner JOIN [Kadry2024v2].[dbo].[O_HDAY02] OTPUSK
ON H1.[O_HMEN01_ID] = OTPUSK.[O_HMEN01_ID] AND H1.[REGION_COD] = OTPUSK.[REGION_COD]
LEFT JOIN [Kadry2024v2].[dbo].[M_HDAY02] OTPUSK_SPRAVOCHNIK
ON OTPUSK.[M_HDAY02_ID] = OTPUSK_SPRAVOCHNIK.[M_HDAY02_ID]

LEFT JOIN [Kadry2024v2].[dbo].[O_ORD_01] DOCUMENTS
ON OTPUSK.[O_ORD_01_ID] = DOCUMENTS.[O_ORD_01_ID] and OTPUSK.[REGION_COD] = DOCUMENTS.[REGION_COD]

WHERE OTPUSK.[M_HDAY02_ID] = 42
Order by H1.[REGION_COD], H1.[O_HMEN01_ID], OTPUSK.[O_HDAY02_ID]
";

?>