<?php

$sql_attestation = "SELECT
H1.[O_HMEN01_ID]
,H1.[REGION_COD]
,ATTEST.[O_HMEN20_ID]
,ATTEST.[M_QUAL04_ID] as COMMISSION_DECISION_CODE
,QUAL.[NAME] as COMMISSION_DECISION
,ATTEST.[MARKDATE] as ATTESTATION_DATE
,ATTEST.[O_ORD_01_ID] as doc_id
,VSE_DOCS.[NAME] as DOC_NAME
,VSE_DOCS.[NUM] as PROTOCOL_NUM
,VSE_DOCS.[DATE] as POTOCOL_DATE
,PRIKAZI.[M_ORD_03_ID] as PROTOCOL_ID
,PRIKAZI.[NAME] as PROTOCOL_NAME

FROM [Kadry2024v2].[dbo].[O_HMEN01] H1

LEFT JOIN [Kadry2024v2].[dbo].[O_HMEN20] ATTEST
ON H1.[REGION_COD] = ATTEST.[REGION_COD] and H1.[O_HMEN01_ID] = ATTEST.[O_HMEN01_ID]

LEFT JOIN [Kadry2024v2].[dbo].[M_QUAL04] QUAL
ON ATTEST.[M_QUAL04_ID] = QUAL.[M_QUAL04_ID]

LEFT JOIN [Kadry2024v2].[dbo].[O_ORD_01] VSE_DOCS
ON H1.[REGION_COD] = VSE_DOCS.[REGION_COD] and ATTEST.[O_ORD_01_ID] = VSE_DOCS.[O_ORD_01_ID]

LEFT JOIN [Kadry2024v2].[dbo].[M_ORD_03] PRIKAZI
ON VSE_DOCS.[M_ORD_03_ID] = PRIKAZI.[M_ORD_03_ID]

WHERE O_HMEN20_ID IS NOT NULL
order by H1.[REGION_COD], H1.[O_HMEN01_ID]
";

  ?>