<?php

$sql_education = "SELECT
H1.[O_HMEN01_ID]
,H1.[REGION_COD]
,EDUCATION.[O_HMEN07_ID]
,EDUCATION_LEVEL.[M_EDU_01_ID] as EDUCATION_LEVEL
,EDUCATION.[ORG] as EDUCATION_ORGANIZATION
,EDUCATION.[SPECIAL] as EDUCATION_SPECIAL
,EDUCATION.[DATEBEGIN] as EDUCATION_BEGIN
,EDUCATION.[DATEFINISH] as EDUCATION_FINISH
,EDUCATION.[SERIA_DOC] as EDUCATION_DOC_SER
,EDUCATION.[NUM_DOC] as EDUCATION_DOC_NUMB
,EDUCATION.[DATE_DOC] as EDUCATION_DOC_DATE
,EDU_10.[NAME] as Qualification
,OKSO.[Cod] as OKSO_COD

  FROM [Kadry2024v2].[dbo].[O_HMEN01] H1
  
  LEFT JOIN [Kadry2024v2].[dbo].[M_EDU_04] EDUCATION_TYPE
  ON H1.[M_EDU_04_ID] = EDUCATION_TYPE.[M_EDU_04_ID]
  
  LEFT JOIN [Kadry2024v2].[dbo].[O_HMEN07] EDUCATION
  ON H1.[O_HMEN01_ID] = EDUCATION.[O_HMEN01_ID] AND H1.[REGION_COD] = EDUCATION.[REGION_COD]

  LEFT JOIN [Kadry2024v2].[dbo].[M_EDU_10] EDU_10
  ON EDUCATION.[M_EDU_10_ID] = EDU_10.[M_EDU_10_ID]
  
  LEFT JOIN [Kadry2024v2].[dbo].[M_EDU_01] EDUCATION_LEVEL
  ON EDUCATION.[M_EDU_01_ID] = EDUCATION_LEVEL.[M_EDU_01_ID]

  LEFT JOIN [Kadry2024v2].[dbo].[M_OKSO] OKSO
  ON EDUCATION.[M_OKSO_SPEC_ID] = OKSO.[M_OKSOID]
  
  Order by H1.[REGION_COD], H1.[O_HMEN01_ID]
";

?>