<?php

$sql_businesstips = "SELECT
H1.[O_HMEN01_ID]
,H1.[REGION_COD]
,KOMMANDIROVKI.[O_HMEN24_ID] as KOMM_ID
,KOMMANDIROVKI.[PLACE_KOM] as KOMM_PLACE
,KOMMANDIROVKI.[REASON] AS KOMM_REASON
,KOMMANDIROVKI.[DATA_C] AS KOMM_BEGIN
,KOMMANDIROVKI.[DATA_PO] AS KOMM_FINISH
,KOMMANDIROVKI.[NUM_DOC] AS KOMM_DOC_NUM
,KOMMANDIROVKI.[DATE_DOC] AS KOM_DOC_DATE
,DOCS.[O_ORD_01_ID] AS DOC_ID
,DOCS.[NAME] AS DOC_NAME
,DOCS.[NUM] AS DOC_NUM
,DOCS.[DATE] AS DOC_DATE

FROM [Kadry2024v2].[dbo].[O_HMEN01] H1

inner JOIN [Kadry2024v2].[dbo].[O_HMEN24] KOMMANDIROVKI
ON H1.[O_HMEN01_ID] = KOMMANDIROVKI.[O_HMEN01_ID] and H1.[REGION_COD] = KOMMANDIROVKI.[REGION_COD]

LEFT JOIN [Kadry2024v2].[dbo].[O_ORD_01] DOCS
ON KOMMANDIROVKI.[O_ORD_01_ID] = DOCS.[O_ORD_01_ID] and KOMMANDIROVKI.[REGION_COD] = DOCS.[REGION_COD]

Order by H1.[REGION_COD], H1.[O_HMEN01_ID], KOMM_ID
";
    
?>