<?php

$sql_workers = "SELECT 
H1.[O_HMEN01_ID]
,H1.[REGION_COD]
,H1.[FSTNAME]
,H1.[FAMILY]
,H1.[LSTNAME]
,WFl.[O_SRT_ID]
,WFl.[DATEFINISH]
,SRT.[NAME]
,SRT.[REGION_COD]
,SRT.[NODE_PAR]
,SRT2.[NAME]
,SRT2.[REGION_COD]
,SRT2.[O_SRT_ID]
,SRT3.[NAME]
,SRT3.[REGION_COD]
,SRT3.[O_SRT_ID]
,SRT4.[NAME]
,SRT4.[REGION_COD]
,SRT4.[O_SRT_ID]
,SRT5.[NAME]
,SRT5.[REGION_COD]
,SRT5.[O_SRT_ID]

FROM [Kadry2024v2].[dbo].[O_HMEN01] H1

LEFT JOIN [Kadry2024v2].[dbo].[O_WFL_01] WFl
ON H1.[O_HMEN01_ID] = WFl.[O_HMEN01_ID] AND H1.[REGION_COD] = WFl.[REGION_COD]

LEFT JOIN [Kadry2024v2].[dbo].[O_SRT] SRT
ON WFl.[O_SRT_ID] = SRT.[O_SRT_ID] AND WFl.[REGION_COD] = SRT.[REGION_COD]

LEFT JOIN [Kadry2024v2].[dbo].[O_SRT] SRT2
ON SRT.[NODE_PAR] = SRT2.[O_SRT_ID] AND SRT.[REGION_COD] = SRT2.[REGION_COD]

LEFT JOIN [Kadry2024v2].[dbo].[O_SRT] SRT3
ON SRT2.[NODE_PAR] = SRT3.[O_SRT_ID] AND SRT2.[REGION_COD] = SRT3.[REGION_COD]

LEFT JOIN [Kadry2024v2].[dbo].[O_SRT] SRT4
ON SRT3.[NODE_PAR] = SRT4.[O_SRT_ID] AND SRT3.[REGION_COD] = SRT4.[REGION_COD]

LEFT JOIN [Kadry2024v2].[dbo].[O_SRT] SRT5
ON SRT4.[NODE_PAR] = SRT5.[O_SRT_ID] AND SRT4.[REGION_COD] = SRT5.[REGION_COD]

WHERE WFl.[O_SRT_ID] IS NOT NULL 
--AND WFl.[DATEFINISH] IS NULL
--and SRT2.[DATEFINISH] is null
--and SRT3.[DATEFINISH] is null
--and SRT4.[DATEFINISH] is null
--and SRT5.[DATEFINISH] is null

Order by H1.[REGION_COD],H1.[O_HMEN01_ID]
";

?>

