<?php

$sql_sick = "SELECT
H1.[O_HMEN01_ID]
,H1.[REGION_COD]
,SICK.[BULLETINID] AS SICK_ID
,SICK.[BULLETINNUM] AS SICK_NUM
,SICK.[DATEBEGIN] AS SICK_BEGIN
,SICK.[DATEEND] AS SICK_END
,SICK.[BULLETINDATE] AS SICK_DATEGIVEN
,SICK.[M_BullReasonID] AS SICK_CODE

FROM [Kadry2024v2].[dbo].[O_HMEN01] H1

inner JOIN [Kadry2024v2].[dbo].[BULLETIN] SICK
ON H1.[O_HMEN01_ID] = SICK.[O_HMEN01_ID] AND H1.[REGION_COD] = SICK.[REGION_COD]

Order by H1.[REGION_COD], H1.[O_HMEN01_ID], SICK_END
";

?>