<?php

$sql_vacations = "SELECT
H1.[O_HMEN01_ID]
,H1.[REGION_COD]
,OTPUSK1.[O_HDAY01_ID]
,OTPUSK1.[DATEBEGIN]
,OTPUSK1.[DATEFINISH]
,OTPUSK1.[USEBDAYCAL]
,OTPUSK1.[USEADAYRAB]
,OTPUSK1.[DATE]
,OTPUSK1.[DATEFACTFINISH]

FROM [Kadry2024v2].[dbo].[O_HMEN01] H1

inner JOIN [Kadry2024v2].[dbo].[O_HDAY01] OTPUSK1
ON H1.[O_HMEN01_ID] = OTPUSK1.[O_HMEN01_ID] AND H1.[REGION_COD] = OTPUSK1.[REGION_COD]

Order by H1.[REGION_COD], H1.[O_HMEN01_ID],OTPUSK1.[O_HDAY01_ID]
"

?>